services:
  frontend:
    image: asadcoder/quirknotes_frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    image: asadcoder/quirknotes_backend:latest
    depends_on:
      - mongodb
    ports: 
      - "4000:4000"
    environment:
      - ENV=Docker
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017" 

